services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: npm run build
  startCommand: npm run start
  autoDeploy: true


- type: web
  name: nextjs-static
  runtime: static
  buildCommand: yarn; yarn build
  staticPublishPath: out
  pullRequestPreviewsEnabled: true     # optional
  